//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstTouchDashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstTouchCertificate
    {
        public int id { get; set; }
        public string propertyid { get; set; }
        public string uprn { get; set; }
        public string addressline1 { get; set; }
        public string certtype { get; set; }
        public string postcode { get; set; }
        public string operativename { get; set; }
        public string tradegroup { get; set; }
        public string eDocsRef { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string cause { get; set; }
    }
}
